### ISSUE TITLE
Perhaps you could use union or std::variant

### ISSUE THREAD

**Issue by oficsu** [Solisuom/SJR#4]
SJR can contain different values at one time because stores mapJson, vectorJson and value regardless of actual SJR::type, but it should not be. In addition, it's expected that we clear content of this containers, but this does not happen

**Comment by LuridHound** [comment]
Okay, I will do it.
But I am going to split in 2 tasks.
**1st**
Create `std::variant<bool,int,float,std::string>`,
because when SJR get value, it always converts value from string to the necessary value, that can by quiet long for some cases.
Commit : 170a2d6ff35018fc3b8fb52ca41be597d6ff35ea
**2nd**
Your original task(except for clearing a content).
Commit : 53501abc79a0ae49f0c446a51a69dea567c48fd3
